export enum Routes {
    Root = '/',
    Login = '/login-next',
    Logout = '/logout',
    Home = '/home',
    Datasets = '/datasets',
    DatasetBase = '/dataset',
    Dataset = `${Routes.DatasetBase}${Routes.DatasetBase}`,
    Agent = '/agent',
    AgentTemplates = '/agent-templates',
    Agents = '/agents',
    Memories = '/memories',
    Memory = '/memory',
    MemoryMessage = '/memory-message',
    MemorySetting = '/memory-setting',
    AgentList = '/agent-list',
    Searches = '/next-searches',
    Search = '/next-search',
    SearchShare = '/next-search/share',
    Chats = '/next-chats',
    Chat = '/next-chat',
    Files = '/files',
    ProfileSetting = '/profile-setting',
    Profile = '/profile',
    Api = '/api',
    Mcp = '/mcp',
    Team = '/team',
    Plan = '/plan',
    Model = '/model',
    Prompt = '/prompt',
    DataSource = '/data-source',
    DataSourceDetailPage = '/data-source-detail-page',
    ProfileMcp = `${ProfileSetting}${Mcp}`,
    ProfileTeam = `${ProfileSetting}${Team}`,
    ProfilePlan = `${ProfileSetting}${Plan}`,
    ProfileModel = `${ProfileSetting}${Model}`,
    ProfilePrompt = `${ProfileSetting}${Prompt}`,
    ProfileProfile = `${ProfileSetting}${Profile}`,
    DatasetTesting = '/testing',
    Chunk = '/chunk',
    ChunkResult = `${Chunk}${Chunk}`,
    Parsed = '/parsed',
    ParsedResult = `${Chunk}${Parsed}`,
    Result = '/result',
    ResultView = `${Chunk}${Result}`,
    KnowledgeGraph = '/knowledge-graph',
    AgentLogPage = '/agent-log-page',
    AgentShare = '/agent/share',
    ChatShare = `${Chats}/share`,
    ChatWidget = `${Chats}/widget`,
    UserSetting = '/user-setting',
    DataSetOverview = '/dataset-overview',
    DataSetSetting = '/dataset-setting',
    DataflowResult = '/dataflow-result',
    Admin = '/admin',
    AdminServices = `${Admin}/services`,
    AdminUserManagement = `${Admin}/users`,
    AdminWhitelist = `${Admin}/whitelist`,
    AdminRoles = `${Admin}/roles`,
    AdminMonitoring = `${Admin}/monitoring`, 
}

const routeConfig = [
    {
      path: '/login',
      Component: lazy(() => import('@/pages/login-next')),
      layout: false,
      errorElement: <FallbackComponent />,
    },
    {
      path: '/login-next',
      Component: lazy(() => import('@/pages/login-next')),
      layout: false,
      errorElement: <FallbackComponent />,
    },
]